### ISSUE TITLE
Publish v2.5.0 to NPM

### ISSUE THREAD

**Issue by paulocoghi** [bluejava/zousan#15]
First of all, thanks for your incredible library! I've [tested](https://jsperf.com/promise-speed-comparison/31) it against more updated versions of Later, When, PinkySwear, BlueBird, etc, and **Zousan is still the fastest** by a large margin!

But the published version on NPM is the 2.3.3, not 2.5.0.

Thanks again!

**Comment by bluejava** [comment]
Thanks Paul! I appreciate the kind words.

Yah, sorry about the delay in publishing. I made the 2.3.3 changes while travelling and didn't have my npm credentials. :-o  Then I forgot when I returned home - so thanks for the reminder!

I've now published 3.0.0.
