### ISSUE TITLE
v3.0.0 can't provide in webpack

### ISSUE THREAD

**Issue by gblok** [bluejava/zousan#16]
``` new ProvidePlugin({Promise: 'zousan'})```
should work?
~v2.3.3 worked

**Comment by gblok** [comment]
still working ```new ProvidePlugin({Promise: ['zousan', 'default']})```

**Comment by bluejava** [comment]
Good catch @gblok . Digging into the webpack docs (https://webpack.js.org/plugins/provide-plugin/) I did find this, which concurs with your solution:

> For importing the default export of an ES2015 module, you have to specify the default property of module.

Thanks for reporting back that it worked!
